### PR TITLE
Bump phoenix_html to v4 and reimplement selects

### PR DESCRIPTION
**Pull request by 03juan**
Bumped phoenix_html to v4 and reimplemented all selects with core Phoenix.HTML functions.

Tested with current `mix.lock` and after `mix deps.update --all`.

Also updated Poison but didn't know how to test it?

### CODE REVIEW

**Comment by 03juan** [comment]
```
~/code/forks/GitHub/03juan/cldr_html bump-phoenix-html-ver*                                                                                        22:56:56
❯ mix hex.outdated

Dependency              Current  Latest  Status      
dialyxir                1.4.3    1.4.3   Up-to-date  
ex_cldr_collation       0.7.2    0.7.2   Up-to-date  
ex_cldr_currencies      2.16.1   2.16.1  Up-to-date  
ex_cldr_locale_display  1.4.1    1.4.1   Up-to-date  
ex_cldr_territories     2.9.0    2.9.0   Up-to-date  
ex_cldr_units           3.17.0   3.17.0  Up-to-date  
ex_doc                  0.33.0   0.33.0  Up-to-date  
ex_money                5.16.1   5.16.1  Up-to-date  
jason                   1.4.1    1.4.1   Up-to-date  
phoenix_html            4.1.1    4.1.1   Up-to-date  
poison                  5.0.0    5.0.0   Up-to-date  

Run `mix hex.outdated APP` to see requirements for a specific dependency.

~/code/forks/GitHub/03juan/cldr_html bump-phoenix-html-ver*                                                                                        22:57:05
❯ mix test

...
compilation logs
...

==> cldr_html
Compiling 6 files (.ex)

22:58:21.582 [info] Downloaded locale :ar

22:58:22.011 [info] Downloaded locale :he

22:58:22.409 [info] Downloaded locale :th

22:58:22.779 [info] Downloaded locale :zh

22:58:23.128 [info] Downloaded locale :"zh-Hans"

22:58:23.477 [info] Downloaded locale :"zh-Hant"
Generating MyApp.Cldr for 8 locales named [:ar, :en, :he, :th, :und, ...] with a default locale named :en
Compiling mix/my_app_cldr.ex (it's taking more than 10s)
Generated cldr_html app
......................
Finished in 0.05 seconds (0.00s async, 0.05s sync)
22 tests, 0 failures

Randomized with seed 541259
```

**Comment by kipcole9** [comment]
@03juan Thanks very much indeed, greatly appreciated! Let me know when you're comfortable you're at a stable point and I'll merge, re-test and release.

**Comment by 03juan** [comment]
@kipcole9 You're very welcome. I'm happy with it now after fixing the oversight of `select_options`.

**Comment by kipcole9** [comment]
Thanks very much again @03juan, merged and will aim to get a release published in the new couple of hours.

**Comment by kipcole9** [comment]
I have published [ex_cldr_html version 1.6.0](https://hex.pm/packages/ex_cldr_html/1.6.0) with the following changelog entry:

### Enhancements

* Adds support for [phoenix_html version 4.0](https://hex.pm/packages/phoenix_html/4.1.1). Thanks very much to @03juan for the PR.

Note that Elixir 1.12 is now a minimum version requirement.

Thanks very much again @03juan.

**Pull request merged**
